Name:           ros-hydro-cob-base-drive-chain
Version:        0.5.5
Release:        0%{?dist}
Summary:        ROS cob_base_drive_chain package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_base_drive_chain
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-cob-canopen-motor
Requires:       ros-hydro-cob-generic-can
Requires:       ros-hydro-cob-srvs
Requires:       ros-hydro-cob-utilities
Requires:       ros-hydro-control-msgs
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-libpcan
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cob-canopen-motor
BuildRequires:  ros-hydro-cob-generic-can
BuildRequires:  ros-hydro-cob-srvs
BuildRequires:  ros-hydro-cob-utilities
BuildRequires:  ros-hydro-control-msgs
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-libntcan
BuildRequires:  ros-hydro-libpcan
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs

%description
This package contains classes that are able to control the platform of the
Care-O-Bot. This means to establish a CAN communication to drive and steering
motors of the platform and later send motion commands and receive motor
information.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Aug 28 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.5-0
- Autogenerated by Bloom

* Mon Aug 25 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.4-0
- Autogenerated by Bloom

