Name:           ros-indigo-cob-driver
Version:        0.6.0
Release:        0%{?dist}
Summary:        ROS cob_driver package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_driver
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-cob-base-drive-chain
Requires:       ros-indigo-cob-camera-sensors
Requires:       ros-indigo-cob-canopen-motor
Requires:       ros-indigo-cob-generic-can
Requires:       ros-indigo-cob-head-axis
Requires:       ros-indigo-cob-light
Requires:       ros-indigo-cob-phidgets
Requires:       ros-indigo-cob-relayboard
Requires:       ros-indigo-cob-sick-lms1xx
Requires:       ros-indigo-cob-sick-s300
Requires:       ros-indigo-cob-sound
Requires:       ros-indigo-cob-undercarriage-ctrl
Requires:       ros-indigo-cob-utilities
Requires:       ros-indigo-cob-voltage-control
BuildRequires:  ros-indigo-catkin

%description
The cob_driver stack includes packages that provide access to the Care-O-bot
hardware through ROS messages, services and actions. E.g. for mobile base, arm,
camera sensors, laser scanners, etc...

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Sep 09 2014 Florian Weisshardt <fmw@ipa.fhg.de> - 0.6.0-0
- Autogenerated by Bloom

* Tue Aug 26 2014 Florian Weisshardt <fmw@ipa.fhg.de> - 0.5.7-0
- Autogenerated by Bloom

