Name:           ros-hydro-cob-canopen-motor
Version:        0.5.4
Release:        0%{?dist}
Summary:        ROS cob_canopen_motor package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_canopen_motor
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-cob-generic-can
Requires:       ros-hydro-cob-utilities
Requires:       ros-hydro-roscpp
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cob-generic-can
BuildRequires:  ros-hydro-cob-utilities
BuildRequires:  ros-hydro-roscpp

%description
The package cob_canopen_motor implements a controller-drive component which is
connected to a can-bus and works with a canopen-interface.
&quot;CanDriveItf&quot; provides a - more or less - generic interface to the
controller-drive components. &quot;CanDrvie...&quot; then implements a specific
setup, e.g. an ELMO Harmonica Controller in case of the
&quot;CanDriveHarmonica&quot;.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Aug 25 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.4-0
- Autogenerated by Bloom

