Name:           ros-hydro-cob-undercarriage-ctrl
Version:        0.5.5
Release:        0%{?dist}
Summary:        ROS cob_undercarriage_ctrl package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_undercarriage_ctrl
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-cob-relayboard
Requires:       ros-hydro-cob-utilities
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cob-relayboard
BuildRequires:  ros-hydro-cob-utilities
BuildRequires:  ros-hydro-control-msgs
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-tf

%description
cob_undercarriage_ctrl implements a controller for the omnidirectional base of
Care-O-bot 3 on joint level. For a given Pltf-Twist the according wheel steering
angles and linear wheel velocities are calculated based on the principle of
rigid body motion. Each joint is than controlled individually to achieve the
computed position and velocity

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Aug 28 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.5-0
- Autogenerated by Bloom

* Mon Aug 25 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.4-0
- Autogenerated by Bloom

