Name:           ros-hydro-cob-generic-can
Version:        0.5.5
Release:        0%{?dist}
Summary:        ROS cob_generic_can package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_generic_can
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-cob-utilities
Requires:       ros-hydro-libntcan
Requires:       ros-hydro-libpcan
Requires:       ros-hydro-roscpp
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cob-utilities
BuildRequires:  ros-hydro-libntcan
BuildRequires:  ros-hydro-libpcan
BuildRequires:  ros-hydro-roscpp

%description
The package cob_generic_can provides an interface for nodes on a can-bus and
examplary wrappers for two PeakSys-can-libs. When a can-bus-device is generated
(for an example see base_dirve_chain) you can use generic_can to create as many
itfs as there will be components communicating via this can-bus. Assign type of
the can communication device (e.g. usb-to-can or can-card of a specific vendor)
and can-address of the target device. This package comes with wrappers for
PeakSys and PeakSysUSB adapters.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Aug 28 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.5-0
- Autogenerated by Bloom

* Mon Aug 25 2014 Matthias Gruhler <mig@ipa.fhg.de> - 0.5.4-0
- Autogenerated by Bloom

